version: '2'
services:
    bookstore-app:
        image: bookstore
        external_links:
            - bookstore-mysql:mysql
            - bookstore-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bookstore?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    bookstore-mysql:
        extends:
            file: mysql.yml
            service: bookstore-mysql
    bookstore-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bookstore-elasticsearch
