version: '2'
services:
    rxmen-app:
        image: rxmen
        external_links:
            - rxmen-mysql:mysql
            - rxmen-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rxmen?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    rxmen-mysql:
        extends:
            file: mysql.yml
            service: rxmen-mysql
    rxmen-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: rxmen-elasticsearch
