# ABMS API default configuration

#
# ==================================================
#  Overridable properties
# ==================================================

# WARNING: Think twice before changing the structure of the "app." section!!!
#
# The following "app" section must contain _only_ the properties
# that are likely to be changed by a user (sysadmin, developer, etc)
# at runtime. These properties will be preserved during upgrades
# on production servers, so it is important that their names
# and interpretation remain stable. These properties may be
# referenced directly from Java code or in subsequent section in this
# file using the ${...} syntax.
#
# The defaults in this file may be overriden with site-specific values in
# property files in the "overrides" folder when running the application
# in development environment.
#
# The example overrides are in git ("overrides.*.example"), while the "overrides"
# directory is .gitignore'd, to avoid merge conflicts.
#
app:
    # APMS database connection parameters
    db:
        url: jdbc:postgresql://localhost/apms
        user: apms
        password: apms

# ==================================================
# Logging defaults
# ==================================================
# These may be overridden in "overrides/logging.properties"
logging:
    # log to console?
    consoleEnabled: true
    # log to console in journald-friendly (Linux) format?
    journaldConsoleEnabled: false
    # log to file?
    fileEnabled: false
    fileMaxSize: 1MB
    fileMaxIndex: 9
    file: logs/abms.log
    # default log levels
    level:
        root: WARN
        ct.app.apms: DEBUG

# ==================================================
#  Spring
# ==================================================
spring:
    application:
        name: apms
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        show-sql: true
        properties:
            hibernate.implicit_naming_strategy: ct.app.apms.config.db.CustomImplicitNamingStrategy
            hibernate.id.new_generator_mappings: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${app.db.url}
        username: ${app.db.user}
        password: ${app.db.password}

    favicon:
        enabled: false
    http:
        multipart.max-file-size: 256KB
        multipart.max-request-size: 256KB
        multipart.enabled: true
        multipart.file-size-threshold: 0
        multipart.location: ${java.io.tmpdir}
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false

# ==================================================
#  Liquibase
# ==================================================
liquibase:
    contexts: dev  # FIXME: unused? maybe remove
    changeLog: classpath:/db/changelog.yml
    enabled: true

# ==================================================
#  APMS
# ==================================================
apms:
    cors:
        allowed-origins: '${app.cors.allowed-origins}'
        allowed-methods: 'GET, PUT, POST, DELETE, OPTIONS'
        allowed-headers: 'Access-Control-Allow-Headers, Origin, X-Requested-With, Content-Type, Accept, Authorization'
        exposed-headers:
        allow-credentials: true
        max-age: 3600
    modules:
        allowed-attachments-content-type:
            certificate-templates:
                'text/plain' : '.txt'
                'application/msword' : '.doc'
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document' : '.docx'
                'application/vnd.ms-excel' : '.xls'
                'application/excel' : '.xls'
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' : '.xlsx'
                'application/pdf' : '.pdf'

